"""Standalone Windows player generated by KeyScore. Python standard library only."""
import ctypes as c
from ctypes import wintypes as w
import json
import time
import sys

SONG = json.loads('__SONG_JSON__')


class KEYBDINPUT(c.Structure):
    _fields_ = [('wVk', w.WORD), ('wScan', w.WORD), ('dwFlags', w.DWORD),
                ('time', w.DWORD), ('dwExtraInfo', c.c_size_t)]


class MOUSEINPUT(c.Structure):
    _fields_ = [('dx', w.LONG), ('dy', w.LONG), ('mouseData', w.DWORD),
                ('dwFlags', w.DWORD), ('time', w.DWORD), ('dwExtraInfo', c.c_size_t)]


class HARDWAREINPUT(c.Structure):
    _fields_ = [('uMsg', w.DWORD), ('wParamL', w.WORD), ('wParamH', w.WORD)]


class INPUTUNION(c.Union):
    _fields_ = [('ki', KEYBDINPUT), ('mi', MOUSEINPUT), ('hi', HARDWAREINPUT)]


class INPUT(c.Structure):
    _anonymous_ = ('data',)
    _fields_ = [('type', w.DWORD), ('data', INPUTUNION)]


SCAN = dict(zip('ASDFGHJQWERTYUI', [0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24,
                                      0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17]))


def play():
    u = c.WinDLL('user32', use_last_error=True)
    u.SendInput.argtypes = [w.UINT, c.POINTER(INPUT), c.c_int]
    u.SendInput.restype = w.UINT
    u.GetAsyncKeyState.argtypes = [c.c_int]
    u.GetAsyncKeyState.restype = w.SHORT
    u.GetForegroundWindow.restype = w.HWND
    held = set()
    target = None

    def send(keys, release=False):
        if not keys:
            return
        if not release:
            held.update(keys)
        items = (INPUT * len(keys))(*[INPUT(type=1, ki=KEYBDINPUT(
            wScan=SCAN[k], dwFlags=0x0008 | (0x0002 if release else 0))) for k in keys])
        c.set_last_error(0)
        if u.SendInput(len(items), items, c.sizeof(INPUT)) != len(items):
            raise RuntimeError(f'Windows rejected input (error {c.get_last_error()}). Check privilege levels.')
        if release:
            held.difference_update(keys)

    def check():
        if u.GetAsyncKeyState(0x1B) & 0x8000:
            raise KeyboardInterrupt
        if target is not None and u.GetForegroundWindow() != target:
            raise RuntimeError('Window focus changed. Playback stopped.')

    def wait(deadline):
        while True:
            check()
            remaining = deadline - time.perf_counter()
            if remaining <= 0:
                return
            time.sleep(min(.005, remaining))

    print('KeyScore:', SONG['title'])
    print('Focus the game instrument. Hold ESC to stop. Changing windows stops playback.')
    try:
        for n in range(SONG['countdown'], 0, -1):
            print(f'Starting in {n}...', flush=True)
            wait(time.perf_counter() + 1)
        target = u.GetForegroundWindow()
        if any(u.GetAsyncKeyState(ord(k)) & 0x8000 for k in SCAN):
            raise RuntimeError('Release all instrument keys before starting.')
        start = time.perf_counter()
        for seconds, releases, presses in SONG['events']:
            wait(start + seconds)
            if time.perf_counter() - (start + seconds) > .5:
                raise RuntimeError('Playback fell behind by over 0.5 seconds; stopped to avoid a burst of keys.')
            send(releases, True)
            send(presses)
        print('Finished.')
    except KeyboardInterrupt:
        print('Stopped.')
    finally:
        for key in list(held):
            try:
                send([key], True)
            except Exception as error:
                print('Could not release', key, ':', error)


if __name__ == '__main__':
    if '--check' in sys.argv:
        print(f"Valid song: {len(SONG['events'])} event groups. No keys sent.")
    else:
        try:
            play()
        except Exception as error:
            print('Playback error:', error)
            input('Press Enter to close...')
